import { describe, it, expect } from "bun:test";
import {
  parseLine,
  parseGCode,
  classifyFeatureType,
  buildPreviewModel,
  getLayer,
  getSegmentsByFeature,
  getZRange,
  estimateSegment,
  estimateAccuracy,
  calculateSeamPositions,
  updateSeamPosition,
  getSeamPositionsForLayer,
  filamentArea,
  extrusionArea,
  distance3D,
  distance2D,
  FEATURE_COLORS,
} from "../src/index";
import type { GCodeCommand, FeatureType, PrintEstimate } from "../src/index";

describe("G-code parser", () => {
  it("parses a simple G1 command", () => {
    const cmd = parseLine("G1 X10.5 Y20.3 Z0.2 E0.05 F1200", 0);
    expect(cmd.command).toBe(1);
    expect(cmd.params["X"]).toBe(10.5);
    expect(cmd.params["Y"]).toBe(20.3);
    expect(cmd.params["Z"]).toBe(0.2);
    expect(cmd.params["E"]).toBe(0.05);
    expect(cmd.params["F"]).toBe(1200);
  });

  it("parses commands with comments", () => {
    const cmd = parseLine("G1 X10 Y20 ; move to position", 0);
    expect(cmd.command).toBe(1);
    expect(cmd.comment).toBe("move to position");
  });

  it("parses comment-only lines", () => {
    const cmd = parseLine("; TYPE:WALL-OUTER", 0);
    expect(cmd.command).toBeUndefined();
    expect(cmd.comment).toBe("TYPE:WALL-OUTER");
  });

  it("parses M commands", () => {
    const cmd = parseLine("M82", 0);
    expect(cmd.command).toBe(82);
  });

  it("parses multiple lines", () => {
    const source = [
      "G28",
      "G1 X10 Y20 E0.1 F1200",
      "; TYPE:INFILL",
      "G1 X30 Y40 E0.2",
      "",
    ].join("\n");
    const commands = parseGCode(source);
    // G28, G1, comment, G1 (empty lines skipped)
    expect(commands.length).toBe(4);
    expect(commands[0].command).toBe(28);
    expect(commands[1].command).toBe(1);
    // commands[2] is the comment line
    expect(commands[2].command).toBeUndefined();
    expect(commands[2].comment).toBe("TYPE:INFILL");
    expect(commands[3].command).toBe(1);
  });
});

describe("Feature type classification", () => {
  it("classifies TYPE:WALL-OUTER", () => {
    const cmd: GCodeCommand = {
      line: 0,
      raw: "",
      params: {},
      comment: "TYPE:WALL-OUTER",
    };
    expect(classifyFeatureType(cmd)).toBe("wall-outer");
  });

  it("classifies TYPE:INFILL", () => {
    const cmd: GCodeCommand = {
      line: 0,
      raw: "",
      params: {},
      comment: "TYPE:INFILL",
    };
    expect(classifyFeatureType(cmd)).toBe("infill");
  });

  it("classifies feature: support", () => {
    const cmd: GCodeCommand = {
      line: 0,
      raw: "",
      params: {},
      comment: "feature: support",
    };
    expect(classifyFeatureType(cmd)).toBe("support");
  });

  it("returns undefined for unrelated comments", () => {
    const cmd: GCodeCommand = {
      line: 0,
      raw: "",
      params: {},
      comment: "generated by NozzleBench",
    };
    expect(classifyFeatureType(cmd)).toBeUndefined();
  });
});

describe("Preview model builder", () => {
  it("builds a preview model from G-code", () => {
    const source = [
      "G28",
      "G1 Z0.2 F600",
      "; TYPE:WALL-OUTER",
      "G1 X10 Y0 Z0.2 E0.5 F1200",
      "G1 X10 Y10 Z0.2 E1.0",
      "G1 X0 Y10 Z0.2 E1.5",
      "G1 X0 Y0 Z0.2 E2.0",
      "; TYPE:INFILL",
      "G1 X5 Y5 Z0.2 E2.5",
      "G1 X5 Y8 Z0.2 E3.0",
    ].join("\n");

    const commands = parseGCode(source);
    const model = buildPreviewModel(commands);

    expect(model.layers.length).toBeGreaterThan(0);
    expect(model.totalFilamentMm).toBeGreaterThan(0);
    expect(model.totalTimeSeconds).toBeGreaterThan(0);

    // Check that segments have correct feature types
    const layer = model.layers[0];
    const wallSegments = layer.segments.filter(
      (s) => s.featureType === "wall-outer",
    );
    expect(wallSegments.length).toBeGreaterThan(0);

    const infillSegments = layer.segments.filter(
      (s) => s.featureType === "infill",
    );
    expect(infillSegments.length).toBeGreaterThan(0);
  });

  it("handles multiple layers", () => {
    const source = [
      "G28",
      "G1 Z0.2 F600",
      "; TYPE:WALL-OUTER",
      "G1 X10 Y0 Z0.2 E0.5 F1200",
      "G1 X10 Y10 Z0.2 E1.0",
      "G1 Z0.4 F600",
      "G1 X0 Y10 Z0.4 E1.5",
      "G1 X0 Y0 Z0.4 E2.0",
    ].join("\n");

    const commands = parseGCode(source);
    const model = buildPreviewModel(commands);

    expect(model.layers.length).toBe(2);
    expect(model.layers[0].z).toBe(0.2);
    expect(model.layers[1].z).toBe(0.4);
  });

  it("getLayer returns correct layer", () => {
    const source = [
      "G28",
      "G1 Z0.2 F600",
      "G1 X10 Y0 Z0.2 E0.5 F1200",
      "G1 Z0.4 F600",
      "G1 X20 Y0 Z0.4 E1.0 F1200",
    ].join("\n");

    const model = buildPreviewModel(parseGCode(source));
    expect(getLayer(model, 0)?.z).toBe(0.2);
    expect(getLayer(model, 1)?.z).toBe(0.4);
    expect(getLayer(model, 99)).toBeUndefined();
  });

  it("getZRange returns correct range", () => {
    const source = [
      "G28",
      "G1 Z0.2 F600",
      "G1 X10 Y0 Z0.2 E0.5 F1200",
      "G1 Z0.4 F600",
      "G1 X20 Y0 Z0.4 E1.0 F1200",
    ].join("\n");

    const model = buildPreviewModel(parseGCode(source));
    const range = getZRange(model);
    expect(range.min).toBe(0.2);
    expect(range.max).toBe(0.4);
  });

  it("getSegmentsByFeature filters correctly", () => {
    const source = [
      "G28",
      "G1 Z0.2 F600",
      "; TYPE:WALL-OUTER",
      "G1 X10 Y0 Z0.2 E0.5 F1200",
      "; TYPE:INFILL",
      "G1 X20 Y0 Z0.2 E1.0 F1200",
    ].join("\n");

    const model = buildPreviewModel(parseGCode(source));
    const layer = model.layers[0];
    const walls = getSegmentsByFeature(layer, "wall-outer");
    const infill = getSegmentsByFeature(layer, "infill");

    expect(walls.length).toBe(1);
    expect(infill.length).toBe(1);
  });

  it("assigns correct colors to feature types", () => {
    expect(FEATURE_COLORS["wall-outer"]).toBe("#FF4444");
    expect(FEATURE_COLORS["infill"]).toBe("#44FF44");
    expect(FEATURE_COLORS["support"]).toBe("#8888FF");
    expect(FEATURE_COLORS["travel"]).toBe("#333333");
  });
});

describe("Print time estimation", () => {
  it("estimates time from segments", () => {
    const segments = [
      {
        start: { x: 0, y: 0, z: 0, e: 0, f: 1200 },
        end: { x: 10, y: 0, z: 0, e: 0.5, f: 1200 },
        featureType: "wall-outer" as FeatureType,
        color: "#FF4444",
      },
    ];

    const estimate = estimateSegment(segments);
    // 10mm at 1200mm/min = 10/1200 min = 0.5s
    expect(estimate.timeSeconds).toBeCloseTo(0.5, 1);
    expect(estimate.filamentMm).toBe(0.5);
    expect(estimate.filamentVolumeMm3).toBeGreaterThan(0);
  });

  it("estimates time for multiple segments", () => {
    const segments = [
      {
        start: { x: 0, y: 0, z: 0, e: 0, f: 1200 },
        end: { x: 10, y: 0, z: 0, e: 0.5, f: 1200 },
        featureType: "wall-outer" as FeatureType,
        color: "#FF4444",
      },
      {
        start: { x: 10, y: 0, z: 0, e: 0.5, f: 2400 },
        end: { x: 10, y: 10, z: 0, e: 1.0, f: 2400 },
        featureType: "infill" as FeatureType,
        color: "#44FF44",
      },
    ];

    const estimate = estimateSegment(segments);
    // First: 10mm at 1200mm/min = 0.5s
    // Second: 10mm at 2400mm/min = 0.25s
    expect(estimate.timeSeconds).toBeCloseTo(0.75, 1);
    // E deltas: (0.5-0) + (1.0-0.5) = 1.0
    expect(estimate.filamentMm).toBeCloseTo(1.0, 2);
  });

  it("estimateAccuracy returns low error for matching estimates", () => {
    const estimate: PrintEstimate = {
      timeSeconds: 100,
      filamentMm: 500,
      filamentVolumeMm3: 1000,
    };
    const reference: PrintEstimate = {
      timeSeconds: 105,
      filamentMm: 510,
      filamentVolumeMm3: 1020,
    };

    const accuracy = estimateAccuracy(estimate, reference);
    expect(accuracy.timeError).toBeCloseTo(0.0476, 3); // ~4.8%
    expect(accuracy.filamentError).toBeCloseTo(0.0196, 3); // ~2%
    expect(accuracy.volumeError).toBeCloseTo(0.0196, 3);
  });
});

describe("Seam painting", () => {
  it("calculates seam positions for a layer", () => {
    const source = [
      "G28",
      "G1 Z0.2 F600",
      "; TYPE:WALL-OUTER",
      "G1 X10 Y0 Z0.2 E0.5 F1200",
      "G1 X10 Y10 Z0.2 E1.0",
      "G1 X0 Y10 Z0.2 E1.5",
      "G1 X0 Y0 Z0.2 E2.0",
    ].join("\n");

    const model = buildPreviewModel(parseGCode(source));
    const seams = calculateSeamPositions(model.layers, "aligned");

    expect(seams.length).toBeGreaterThan(0);
    expect(seams[0].layerIndex).toBe(0);
    expect(seams[0].x).toBeDefined();
    expect(seams[0].y).toBeDefined();
  });

  it("uses nearest strategy", () => {
    const source = [
      "G28",
      "G1 Z0.2 F600",
      "; TYPE:WALL-OUTER",
      "G1 X10 Y0 Z0.2 E0.5 F1200",
      "G1 X10 Y10 Z0.2 E1.0",
      "G1 X0 Y10 Z0.2 E1.5",
      "G1 X0 Y0 Z0.2 E2.0",
    ].join("\n");

    const model = buildPreviewModel(parseGCode(source));
    const seams = calculateSeamPositions(model.layers, "nearest", 5, 5);

    expect(seams.length).toBeGreaterThan(0);
    expect(seams[0].override).toBe("nearest");
  });

  it("updates seam position override", () => {
    const seams = [
      {
        x: 0,
        y: 0,
        z: 0.2,
        layerIndex: 0,
        segmentIndex: 0,
        override: "aligned" as const,
      },
    ];

    const updated = updateSeamPosition(seams, 0, 0, "user");
    expect(updated[0].override).toBe("user");

    // Unrelated seam unchanged
    const seams2 = [
      { x: 0, y: 0, z: 0.2, layerIndex: 0, segmentIndex: 0 },
      { x: 5, y: 5, z: 0.2, layerIndex: 0, segmentIndex: 1 },
    ];
    const updated2 = updateSeamPosition(seams2, 0, 0, "user");
    expect(updated2[0].override).toBe("user");
    expect(updated2[1].override).toBeUndefined();
  });

  it("getSeamPositionsForLayer filters correctly", () => {
    const seams = [
      { x: 0, y: 0, z: 0.2, layerIndex: 0, segmentIndex: 0 },
      { x: 5, y: 5, z: 0.4, layerIndex: 1, segmentIndex: 0 },
    ];

    const layer0 = getSeamPositionsForLayer(seams, 0);
    expect(layer0.length).toBe(1);
    expect(layer0[0].layerIndex).toBe(0);

    const layer1 = getSeamPositionsForLayer(seams, 1);
    expect(layer1.length).toBe(1);
    expect(layer1[0].layerIndex).toBe(1);
  });
});

describe("Utility functions", () => {
  it("filamentArea calculates correctly", () => {
    // 1.75mm diameter: π * (1.75/2)² ≈ 2.405 mm²
    const area = filamentArea(1.75);
    expect(area).toBeCloseTo(2.405, 2);
  });

  it("extrusionArea calculates correctly", () => {
    // 0.4mm nozzle × 0.2mm layer = 0.08 mm²
    const area = extrusionArea(0.4, 0.2);
    expect(area).toBeCloseTo(0.08, 3);
  });

  it("distance3D calculates correctly", () => {
    const d = distance3D({ x: 0, y: 0, z: 0 }, { x: 3, y: 4, z: 0 });
    expect(d).toBeCloseTo(5, 2);
  });

  it("distance2D calculates correctly", () => {
    const d = distance2D({ x: 0, y: 0 }, { x: 3, y: 4 });
    expect(d).toBeCloseTo(5, 2);
  });
});

describe("Integration: sliced model → correct preview data model", () => {
  it("produces complete preview from realistic G-code", () => {
    // Simulate a multi-layer G-code with feature types
    const lines: string[] = [
      "G28 ; home",
      "G1 Z0.2 F600 ; move to first layer",
      "",
      "; LAYER:1",
      "; TYPE:WALL-OUTER",
      "G1 X10 Y0 Z0.2 E0.5 F1200",
      "G1 X10 Y20 Z0.2 E1.5",
      "G1 X0 Y20 Z0.2 E2.5",
      "G1 X0 Y0 Z0.2 E3.5",
      "",
      "; TYPE:WALL-INNER",
      "G1 X2 Y2 Z0.2 E3.7 F1200",
      "G1 X8 Y2 Z0.2 E4.2",
      "G1 X8 Y18 Z0.2 E5.2",
      "G1 X2 Y18 Z0.2 E6.2",
      "G1 X2 Y2 Z0.2 E6.7",
      "",
      "; TYPE:INFILL",
      "G1 X3 Y3 Z0.2 E6.8 F2400",
      "G1 X7 Y3 Z0.2 E7.0",
      "G1 X7 Y7 Z0.2 E7.2",
      "G1 X3 Y7 Z0.2 E7.4",
      "",
      "; LAYER:2",
      "G1 Z0.4 F600",
      "; TYPE:WALL-OUTER",
      "G1 X10 Y0 Z0.4 E8.0 F1200",
      "G1 X10 Y20 Z0.4 E9.0",
      "G1 X0 Y20 Z0.4 E10.0",
      "G1 X0 Y0 Z0.4 E11.0",
      "",
      "; TYPE:INFILL",
      "G1 X3 Y3 Z0.4 E11.2 F2400",
      "G1 X7 Y3 Z0.4 E11.4",
      "G1 X7 Y7 Z0.4 E11.6",
    ];

    const source = lines.join("\n");
    const commands = parseGCode(source);
    const model = buildPreviewModel(commands);

    // Should have 2 layers
    expect(model.layers.length).toBe(2);
    expect(model.layers[0].z).toBeCloseTo(0.2, 1);
    expect(model.layers[1].z).toBeCloseTo(0.4, 1);

    // Total extrusion should be positive
    expect(model.totalFilamentMm).toBeCloseTo(11.6, 1);

    // Print time should be positive
    expect(model.totalTimeSeconds).toBeGreaterThan(0);

    // Each layer should have segments
    for (const layer of model.layers) {
      expect(layer.segments.length).toBeGreaterThan(0);
    }

    // Feature types should be present
    const allSegments = model.layers.flatMap((l) => l.segments);
    const featureTypes = new Set(allSegments.map((s) => s.featureType));
    expect(featureTypes.has("wall-outer")).toBe(true);
    expect(featureTypes.has("infill")).toBe(true);

    // Estimate accuracy should be within 5% (trivial case: estimate IS the reference)
    const estimate = estimateSegment(allSegments);
    const accuracy = estimateAccuracy(estimate, {
      timeSeconds: model.totalTimeSeconds,
      filamentMm: model.totalFilamentMm,
      filamentVolumeMm3: model.totalFilamentVolumeMm3,
    });
    expect(accuracy.timeError).toBeLessThan(0.05);
    expect(accuracy.filamentError).toBeLessThan(0.05);

    // Seam positions should be calculable
    const seams = calculateSeamPositions(model.layers, "aligned");
    expect(seams.length).toBeGreaterThan(0);
  });
});
